---

- name: "Creating AWS Simple Infra Using Ansible Playbook"
  hosts: localhost
  vars:
    project: "OLA"
    instance_type: "t2.micro"
    instance_ami: "ami-0e0ff68cb8e9a188a"
  environment:
    AWS_ACCESS_KEY: "AKIAPSC43FJ"
    AWS_SECRET_KEY: "aPXYPZjp536hH/kY1Lm8"
    AWS_REGION: "ap-south-1"

  tasks:

    - name: " AWS Infra - Creating KEYPAIR FOR ssh access"
      amazon.aws.ec2_key:
        name: "{{project}}"
        state: present
        tags:
          Name: "{{ project }}"
          project: "{{ project }}"

      register: keypair_status


    - name: "AWS Infra - Saving the keypair private Part Of {{ project }}.pem to local PC"
      when: keypair_status.changed == true
      copy:
        content: "{{ keypair_status.key.private_key}}"
        dest: "{{ project }}.pem"
        mode: 0400

    - name:  "AWS Infra - Creating webserver security group"
      amazon.aws.ec2_group:
        name: "{{ project }}-webserver"
        description: "allows 80,443 "

        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0

          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        tags:
          Name: "{{ project }}-webserver"
          project: "{{ project }}"
      register: webserver

    - name:  " AWS Infra - Creating another remote security group"
      amazon.aws.ec2_group:
        name: "{{ project }}-remote"
        description: "allows 22 for ssh"

        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

        tags:
          Name: "{{ project }}-remote"
          project: "{{ project }}"
      register: remote


    - name:  " AWS Infra - Creating Ec2 Instance for Installing the webserver"
      amazon.aws.ec2:
        key_name: "{{ keypair_status.key.name}}"
        instance_type: "{{ instance_type }}"
        image: "{{ instance_ami }}"
        wait: yes
        group_id:
          - "{{ webserver.group_id }}"
          - "{{ remote.group_id }}"
        instance_tags:
          Name: "{{ project }}-webserver"
          project: "{{ project }}"
        count_tag:
          Name: "{{ project }}-webserver"
        exact_count: 2
      register: if_ec2_status

    - name: "AWS Infra - Creating Dynamic Inventory for the EC2 creation"
      add_host:
        name: "{{ item.public_ip }}"
        groups: "amazon"
        ansible_host: "{{ item.public_ip }}"
        ansible_port: 22
        ansible_user: "ec2-user"
        ansible_ssh_private_key_file: "{{ project }}.pem"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      with_items:
        - "{{ if_ec2_status.tagged_instances }}"

    -  name: "AWS Infra - Waiting for instances to become Online. Please wait"
       when: if_ec2_status.changed == true
       wait_for:
         timeout: 90


- name: " AWS Infra - Ec2 Instances Provisioning"
  hosts: amazon
  become: true
  tasks:

    - name: "AWS Infra - Installing apache webserver"
      yum:
        name: httpd
        state: present

    - name: "AWS Infra - Creating simple index.html"
      copy:
        content: "<center><h1> Welcome back {{ ansible_hostname }}</h1></center>"
        dest: /var/www/html/index.html

    - name: "AWS Infra - restart and enable httpd"
      service:
        name: httpd
        state: restarted
        enabled: true

    - name: "AWS Infra - Website - url for check"
      run_once: true
      debug:
        msg: "http://{{item}}"
      with_items:
        - "{{ groups.amazon }}"
